import Head from 'next/head'
import Image from 'next/image'
import BWImage from "../src/components/BWImage";
import Footer from "../src/components/Footer";
import TopNav from "../src/components/TopNav";
import Product from "../src/components/Product";

export default function Home() {
  return (
    <div>
      <Head>
        <title>nETHer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopNav />
      <main >
        <h1>
          Welcome to nETHer
        </h1>

      {/*  a square box*/}
        <div className={"flex gap-4"}>
          <BWImage src="https://images.unsplash.com/profile-fb-1514888261-0e72294039e0.jpg?ixlib=rb-1.2.1&crop=faces&fit=crop&w=32&h=32" alt="box" width={200} height={200} />
          <BWImage src="/cards.jpg" alt="box" width={200} height={200} effectType="backdropRollUp" />
          <BWImage src="/example2.bmp" alt="box" width={200} height={200} />
          <Product src="/example2.bmp"
                  alt="box"
                  effectType="backdropRollUp"
                  name="Example 2"
                  brand="Brand Name"
                  price={100}
          />
        </div>


      </main>

      <button className="btn">Btn</button>


      <Footer />

    </div>
  )
}
