import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import BWImage from "../src/components/BWImage";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

      {/*  a square box*/}
        <div className={styles.box}>
          <BWImage src="/cards.jpg" alt="box" width={200} height={200} />
          <BWImage src="/cards.jpg" alt="box" width={200} height={200} />
          <BWImage src="/cards.jpg" alt="box" width={200} height={200} />
        </div>


      </main>


    </div>
  )
}
